# Power Tools version stamp — must match `version` in package.json.
# CI enforces that (see .github/workflows/release.yml, "Verify
# bridge_version.py matches package.json version"), so a release fails
# rather than shipping a drifted stamp. Update this in the same commit as
# the package.json bump.
#
# WHY IT MATTERS: this is a plain incrementing semver, and init_unreal.py's
# bridge self-sync compares this exact stamp between the project copy and
# the engine copy to decide whether to copy newer tools over older ones. If
# the two ever diverged, that comparison would be meaningless. They did
# diverge once — this file sat at 0.1.1 through the 0.1.4 release, because
# it was documented as generated by a scripts/release.mjs that does not
# exist in this repo and nothing verified it. Hence the CI check.
BRIDGE_VERSION = "0.1.5"
