# GENERATED by scripts/release.mjs at version bump — do not edit by hand.
# Staged into <project>/Content/Python with the rest of the bridge so the
# extension can compare staged vs shipped copies and flag stale installs.
BRIDGE_VERSION = "0.0.510"
