# GENERATED by scripts/release.mjs at version bump — do not edit by hand.
# This is the Power Tools DATE version (YYYY.M.D) -- NOT the TycoonAgents
# extension semver. It is the bridge's one identity whether it was staged
# by the VS Code extension or installed from the standalone release, so a
# standalone user never sees a version tied to a product they don't have.
BRIDGE_VERSION = "2026.8.21"
